services:
  - type: web
    name: my-app
    env: rust
    buildCommand: "cargo build --release"
    startCommand: "cargo run --bin verifier"
    envVars:
      - key: RUST_LOG
        value: info
    filePaths:
      - /opt/render/project/src/frontend/verifier
